<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="1" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-28T15:16:39Z" name="Default suite" finished-at="2024-06-28T15:16:56Z" duration-ms="16739">
    <groups>
    </groups>
    <test started-at="2024-06-28T15:16:39Z" name="Default test" finished-at="2024-06-28T15:16:56Z" duration-ms="16739">
      <class name="selenium01.test01">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:39Z" name="initDriver" finished-at="2024-06-28T11:16:42Z" duration-ms="2414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testAmountMandatoryField()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:42Z" name="testAmountMandatoryField" finished-at="2024-06-28T11:16:42Z" duration-ms="620" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ERROR: Missing Amount, mandatory field] but found [SUCCESS MESSAGE, invoice abc123 has been created]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ERROR: Missing Amount, mandatory field] but found [SUCCESS MESSAGE, invoice abc123 has been created]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at selenium01.test01.testAmountMandatoryField(test01.java:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAmountMandatoryField -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:42Z" name="closeWindow" finished-at="2024-06-28T11:16:42Z" duration-ms="57" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:42Z" name="initDriver" finished-at="2024-06-28T11:16:44Z" duration-ms="1566" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testDateMandatoryField()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:44Z" name="testDateMandatoryField" finished-at="2024-06-28T11:16:44Z" duration-ms="586" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ERROR: Missing date, mandatory field] but found [SUCCESS MESSAGE, invoice abc123 has been created]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ERROR: Missing date, mandatory field] but found [SUCCESS MESSAGE, invoice abc123 has been created]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at selenium01.test01.testDateMandatoryField(test01.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDateMandatoryField -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:44Z" name="closeWindow" finished-at="2024-06-28T11:16:44Z" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:44Z" name="initDriver" finished-at="2024-06-28T11:16:46Z" duration-ms="1651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testInvoiceMandatoryField()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:46Z" name="testInvoiceMandatoryField" finished-at="2024-06-28T11:16:47Z" duration-ms="599" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ERROR: Missing invoice, mandatory field] but found [SUCCESS MESSAGE, invoice has been created]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ERROR: Missing invoice, mandatory field] but found [SUCCESS MESSAGE, invoice has been created]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at selenium01.test01.testInvoiceMandatoryField(test01.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvoiceMandatoryField -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:47Z" name="closeWindow" finished-at="2024-06-28T11:16:47Z" duration-ms="56" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:47Z" name="initDriver" finished-at="2024-06-28T11:16:48Z" duration-ms="1576" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testProductMandatoryField()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:48Z" name="testProductMandatoryField" finished-at="2024-06-28T11:16:49Z" duration-ms="564" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ERROR: Missing Product, mandatory field] but found [SUCCESS MESSAGE, invoice abc123 has been created]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ERROR: Missing Product, mandatory field] but found [SUCCESS MESSAGE, invoice abc123 has been created]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at selenium01.test01.testProductMandatoryField(test01.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductMandatoryField -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:49Z" name="closeWindow" finished-at="2024-06-28T11:16:49Z" duration-ms="60" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:49Z" name="initDriver" finished-at="2024-06-28T11:16:50Z" duration-ms="1536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testQuantity()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:50Z" name="testQuantity" finished-at="2024-06-28T11:16:51Z" duration-ms="593" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ERROR: Quantity cannot be zero or empty value.] but found [[[ChromeDriver: chrome on windows (fcbc9628b259fb564125c65f20d1eb1b)] -> id: message]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ERROR: Quantity cannot be zero or empty value.] but found [[[ChromeDriver: chrome on windows (fcbc9628b259fb564125c65f20d1eb1b)] -> id: message]]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at selenium01.test01.testQuantity(test01.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testQuantity -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:51Z" name="closeWindow" finished-at="2024-06-28T11:16:51Z" duration-ms="55" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:51Z" name="initDriver" finished-at="2024-06-28T11:16:53Z" duration-ms="1638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testQuantityDefaultValue()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:53Z" name="testQuantityDefaultValue" finished-at="2024-06-28T11:16:53Z" duration-ms="650" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at selenium01.test01.testQuantityDefaultValue(test01.java:301)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testQuantityDefaultValue -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:53Z" name="closeWindow" finished-at="2024-06-28T11:16:53Z" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:53Z" name="initDriver" finished-at="2024-06-28T11:16:55Z" duration-ms="1589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="testSuccessInvoice()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:55Z" name="testSuccessInvoice" finished-at="2024-06-28T11:16:56Z" duration-ms="643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessInvoice -->
        <test-method is-config="true" signature="closeWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:56Z" name="closeWindow" finished-at="2024-06-28T11:16:56Z" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeWindow -->
        <test-method is-config="true" signature="quitWindow()[pri:0, instance:selenium01.test01@c7ba306]" started-at="2024-06-28T11:16:56Z" name="quitWindow" finished-at="2024-06-28T11:16:56Z" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitWindow -->
      </class> <!-- selenium01.test01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
